## Bonus Challenge Four: Processing Streaming Data

### Install dependencies

In [1]:
# google-cloud-bigquery and google-cloud-pubsub provide the BigQuery + Pub/Sub clients.
%pip install --quiet --upgrade google-cloud-bigquery google-cloud-pubsub db-dtypes

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.8/324.8 kB 7.7 MB/s eta 0:00:00

In [2]:
from google.cloud import bigquery
from google.cloud import pubsub_v1

### Variables

In [3]:
import os

# --- Diagnostic: shows what each detection method returns ---
print("=== Project detection diagnostic ===")
print("env GOOGLE_CLOUD_PROJECT:", os.environ.get("GOOGLE_CLOUD_PROJECT"))
print("env GCP_PROJECT         :", os.environ.get("GCP_PROJECT"))
try:
    import google.auth
    _creds, _proj = google.auth.default()
    print("google.auth project     :", _proj)
except Exception as e:
    print("google.auth failed      :", e)
print("=" * 36)


def detect_project_id():
    # 1. Explicit env var wins (lets anyone override without editing code)
    env = os.environ.get("GOOGLE_CLOUD_PROJECT") or os.environ.get("GCP_PROJECT")
    if env:
        return env
    # 2. Ask Application Default Credentials what project we're running under
    try:
        import google.auth
        _, project = google.auth.default()
        if project:
            return project
    except Exception:
        pass
    # 3. Last resort: query the metadata server (works on GCP runtimes)
    try:
        import urllib.request
        req = urllib.request.Request(
            "http://metadata.google.internal/computeMetadata/v1/project/project-id",
            headers={"Metadata-Flavor": "Google"},
        )
        return urllib.request.urlopen(req, timeout=2).read().decode()
    except Exception:
        return None


class Config:
    """Immutable run config. `project_id` is YOUR billing project (auto-detected).
    The Pub/Sub topic lives in a DIFFERENT project (paul-leroy) that we only subscribe to."""

    def __init__(
        self,
        project_id=None,                       # None -> auto-detect your billing project
        dataset="transponder_data_colab",
        location="US",
        table_name="flight_transponder_msgs",
        # --- Pub/Sub source (provided by the challenge) ---
        pubsub_project="paul-leroy",
        topic_name="flight-transponder",
        subscription_name=None,                # None -> auto-generate a unique pull subscription
    ):
        resolved = project_id or detect_project_id()
        if not resolved:
            raise ValueError(
                "Could not determine project_id. Pass it explicitly: "
                "Config(project_id='my-project')"
            )
        import uuid as _uuid
        sub = subscription_name or f"flight-transponder-sub-{_uuid.uuid4().hex[:8]}"
        # bypass our own __setattr__ block during construction
        for k, v in {
            "project_id": resolved, "dataset": dataset, "location": location,
            "table_name": table_name, "pubsub_project": pubsub_project,
            "topic_name": topic_name, "subscription_name": sub,
        }.items():
            object.__setattr__(self, k, v)

    def __setattr__(self, name, value):
        raise AttributeError(f"Config is immutable; can't set {name!r}")

    @property
    def table(self):
        return f"{self.project_id}.{self.dataset}.{self.table_name}"

    @property
    def topic_path(self):
        return f"projects/{self.pubsub_project}/topics/{self.topic_name}"

    @property
    def subscription_path(self):
        # Subscription is created in YOUR project, attached to the source topic.
        return f"projects/{self.project_id}/subscriptions/{self.subscription_name}"


CFG = Config()

print("\nProject      :", CFG.project_id)
print("Table        :", CFG.table)
print("Source topic :", CFG.topic_path)
print("Subscription :", CFG.subscription_path)

=== Project detection diagnostic ===
env GOOGLE_CLOUD_PROJECT: qwiklabs-gcp-01-5fe45b5e4e14
env GCP_PROJECT         : None
google.auth project     : qwiklabs-gcp-01-5fe45b5e4e14
====================================

Project      : qwiklabs-gcp-01-5fe45b5e4e14
Table        : qwiklabs-gcp-01-5fe45b5e4e14.transponder_data_colab.flight_transponder_msgs
Source topic : projects/paul-leroy/topics/flight-transponder
Subscription : projects/qwiklabs-gcp-01-5fe45b5e4e14/subscriptions/flight-transponder-sub-e64e3ef0

### Logging

In [4]:
import logging, json, sys, uuid, datetime as dt

logger = logging.getLogger("flight_transponder_stream")
logger.setLevel(logging.INFO)
if not logger.handlers:
    h = logging.StreamHandler(sys.stdout)
    h.setFormatter(logging.Formatter("%(asctime)s | %(levelname)s | %(message)s"))
    logger.addHandler(h)

RUN_ID = str(uuid.uuid4())

def log_event(step: str, status: str, **kw):
    logger.info(json.dumps({"run_id": RUN_ID, "step": step, "status": status, **kw}))

log_event("init", "ok", started=dt.datetime.now(dt.timezone.utc).isoformat())

2026-06-02 19:49:33,147 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "init", "status": "ok", "started": "2026-06-02T19:49:33.147928+00:00"}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "init", "status": "ok", "started": "2026-06-02T19:49:33.147928+00:00"}

### Pipeline: Pub/Sub -> parse -> BigQuery

In [5]:
import time


class TransponderStreamPipeline:
    """Creates a BigQuery table for SBS transponder messages, pulls the streaming
    CSV feed from a Pub/Sub topic, parses each message into the 22-field schema,
    and stream-inserts the rows into BigQuery for querying and Geo Viz."""

    # 22-field SBS BaseStation schema. Order matches the CSV stream exactly so we
    # can zip the split CSV fields straight onto these columns.
    SCHEMA = [
        bigquery.SchemaField("MT",   "STRING",  mode="NULLABLE", description="SEL ID AIR STA CLK MSG info http://woodair.net/sbs/Article/Barebones42_Socket_Data.htm"),
        bigquery.SchemaField("TT",   "INT64",   mode="NULLABLE", description="1 - 8"),
        bigquery.SchemaField("SID",  "STRING",  mode="NULLABLE", description="Database Session record number"),
        bigquery.SchemaField("AID",  "STRING",  mode="NULLABLE", description="Database Aircraft record number"),
        bigquery.SchemaField("Hex",  "STRING",  mode="NULLABLE", description="Aircraft Mode S hexadecimal code https://opensky-network.org/datasets/metadata/"),
        bigquery.SchemaField("FID",  "STRING",  mode="NULLABLE", description="Database Flight record number"),
        bigquery.SchemaField("DMG",  "DATE",    mode="NULLABLE", description="Date message generated"),
        bigquery.SchemaField("TMG",  "TIME",    mode="NULLABLE", description="Time message generated"),
        bigquery.SchemaField("DML",  "DATE",    mode="NULLABLE", description="Date message logged"),
        bigquery.SchemaField("TML",  "TIME",    mode="NULLABLE", description="Time message logged"),
        bigquery.SchemaField("CS",   "STRING",  mode="NULLABLE", description="Callsign (flight number or registration)"),
        bigquery.SchemaField("Alt",  "INT64",   mode="NULLABLE", description="Mode C altitude (Flight Level)"),
        bigquery.SchemaField("GS",   "INT64",   mode="NULLABLE", description="Ground Speed"),
        bigquery.SchemaField("Trk",  "INT64",   mode="NULLABLE", description="Track"),
        bigquery.SchemaField("Lat",  "FLOAT64", mode="NULLABLE", description="Latitude (N/E positive, S/W negative)"),
        bigquery.SchemaField("Lng",  "FLOAT64", mode="NULLABLE", description="Longitude (N/E positive, S/W negative)"),
        bigquery.SchemaField("VR",   "INT64",   mode="NULLABLE", description="Vertical Rate"),
        bigquery.SchemaField("Sq",   "STRING",  mode="NULLABLE", description="Assigned Mode A squawk code"),
        bigquery.SchemaField("Alrt", "INT64",   mode="NULLABLE", description="Flag to indicate squawk has changed"),
        bigquery.SchemaField("Emer", "INT64",   mode="NULLABLE", description="Flag to indicate emergency code has been set"),
        bigquery.SchemaField("SPI",  "INT64",   mode="NULLABLE", description="Flag to indicate transponder Ident has been activated"),
        bigquery.SchemaField("Gnd",  "INT64",   mode="NULLABLE", description="Flag to indicate ground squat switch is active"),
    ]

    # Column name -> BigQuery type, used to coerce each CSV field to the right Python type.
    FIELD_TYPES = [(f.name, f.field_type) for f in SCHEMA]

    def __init__(self, cfg: Config):
        self.cfg = cfg
        self.client = bigquery.Client(project=cfg.project_id, location=cfg.location)
        self.subscriber = pubsub_v1.SubscriberClient()
        self.rows_inserted = 0
        self.messages_seen = 0
        self.parse_errors = 0

    # ---- BigQuery setup -------------------------------------------------
    def ensure_dataset(self):
        ds = bigquery.Dataset(f"{self.cfg.project_id}.{self.cfg.dataset}")
        ds.location = self.cfg.location
        self.client.create_dataset(ds, exists_ok=True)
        log_event("dataset_ready", "ok", dataset=self.cfg.dataset)

    def ensure_table(self):
        table = bigquery.Table(self.cfg.table, schema=self.SCHEMA)
        self.client.create_table(table, exists_ok=True)
        log_event("table_ready", "ok", table=self.cfg.table, fields=len(self.SCHEMA))

    # ---- Pub/Sub setup --------------------------------------------------
    def ensure_subscription(self):
        """Create a pull subscription in our project attached to the source topic."""
        try:
            self.subscriber.create_subscription(
                request={
                    "name": self.cfg.subscription_path,
                    "topic": self.cfg.topic_path,
                    "ack_deadline_seconds": 30,
                }
            )
            log_event("subscription_created", "ok", sub=self.cfg.subscription_path)
        except Exception as e:
            # AlreadyExists is fine; re-raise anything else (e.g. permissions).
            if "AlreadyExists" in type(e).__name__ or "already exists" in str(e).lower():
                log_event("subscription_created", "exists", sub=self.cfg.subscription_path)
            else:
                raise

    # ---- Parsing --------------------------------------------------------
    @staticmethod
    def _coerce(value, bq_type):
        """Convert a raw CSV field to the Python type BigQuery expects.
        Empty strings -> None (the feed leaves most fields blank)."""
        if value is None:
            return None
        value = value.strip()
        if value == "":
            return None
        try:
            if bq_type == "INT64":
                return int(value)
            if bq_type == "FLOAT64":
                return float(value)
            if bq_type == "DATE":
                # feed uses YYYY/MM/DD -> ISO YYYY-MM-DD
                return value.replace("/", "-")
            if bq_type == "TIME":
                # HH:MM:SS.mmm is already valid BigQuery TIME
                return value
            return value  # STRING
        except (ValueError, TypeError):
            return None

    def parse_message(self, raw: str):
        """Turn one CSV transponder line into a dict keyed by schema column names.
        Returns None if the field count doesn't match the 22-field schema."""
        fields = raw.strip().split(",")
        if len(fields) != len(self.FIELD_TYPES):
            return None
        return {
            name: self._coerce(fields[i], bq_type)
            for i, (name, bq_type) in enumerate(self.FIELD_TYPES)
        }

    # ---- Streaming loop -------------------------------------------------
    def collect(self, run_seconds: int = 180, batch_size: int = 200,
                max_messages_per_pull: int = 100):
        """Pull from the subscription for `run_seconds`, parsing and stream-inserting
        rows into BigQuery in batches. Then stop. (Step 4: run a few minutes, then stop.)"""
        deadline = time.time() + run_seconds
        buffer = []
        log_event("collect_start", "ok", run_seconds=run_seconds)

        while time.time() < deadline:
            resp = self.subscriber.pull(
                request={
                    "subscription": self.cfg.subscription_path,
                    "max_messages": max_messages_per_pull,
                },
                timeout=30,
            )
            if not resp.received_messages:
                continue

            ack_ids = []
            for rm in resp.received_messages:
                ack_ids.append(rm.ack_id)
                self.messages_seen += 1
                raw = rm.message.data.decode("utf-8", errors="replace")
                # A single Pub/Sub message may carry one or several CSV lines.
                for line in raw.splitlines():
                    if not line.strip():
                        continue
                    row = self.parse_message(line)
                    if row is None:
                        self.parse_errors += 1
                        continue
                    buffer.append(row)

            # Acknowledge so messages aren't redelivered.
            self.subscriber.acknowledge(
                request={"subscription": self.cfg.subscription_path, "ack_ids": ack_ids}
            )

            if len(buffer) >= batch_size:
                self._flush(buffer)
                buffer = []

        if buffer:
            self._flush(buffer)

        log_event("collect_done", "ok", messages_seen=self.messages_seen,
                  rows_inserted=self.rows_inserted, parse_errors=self.parse_errors)

    def _flush(self, rows):
        errors = self.client.insert_rows_json(self.cfg.table, rows)
        if errors:
            log_event("flush", "error", count=len(errors), sample=errors[:2])
        else:
            self.rows_inserted += len(rows)
            log_event("flush", "ok", inserted=len(rows), total=self.rows_inserted)

    # ---- Queries --------------------------------------------------------
    def count_records(self):
        df = self.client.query(
            f"SELECT COUNT(*) AS record_count FROM `{self.cfg.table}`"
        ).to_dataframe()
        log_event("count_records", "ok", count=int(df.iloc[0]["record_count"]))
        return df

    def preview(self, n: int = 10):
        df = self.client.query(
            f"SELECT * FROM `{self.cfg.table}` LIMIT {n}"
        ).to_dataframe()
        log_event("preview", "ok", rows=len(df))
        return df

    def locations(self):
        """Step 6: return ST_GEOGPOINT locations for every message with coordinates.
        This is the query to open in Geo Viz."""
        sql = f"""
        SELECT
          ST_GEOGPOINT(Lng, Lat) AS Location
        FROM `{self.cfg.table}`
        WHERE Lat IS NOT NULL
          AND Lng IS NOT NULL
        """
        df = self.client.query(sql).to_dataframe()
        log_event("locations", "ok", points=len(df))
        return df

    def cleanup_subscription(self):
        """Optional: delete the temporary pull subscription when done."""
        try:
            self.subscriber.delete_subscription(
                request={"subscription": self.cfg.subscription_path}
            )
            log_event("cleanup_subscription", "ok")
        except Exception as e:
            log_event("cleanup_subscription", "skip", reason=str(e))

### Setup: dataset + table

In [6]:
pipeline = TransponderStreamPipeline(CFG)
pipeline.ensure_dataset()
pipeline.ensure_table()
print(f"Table ready: {CFG.table}")

2026-06-02 19:50:38,461 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "dataset_ready", "status": "ok", "dataset": "transponder_data_colab"}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "dataset_ready", "status": "ok", "dataset": "transponder_data_colab"}

2026-06-02 19:50:38,829 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "table_ready", "status": "ok", "table": "qwiklabs-gcp-01-5fe45b5e4e14.transponder_data_colab.flight_transponder_msgs", "fields": 22}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "table_ready", "status": "ok", "table": "qwiklabs-gcp-01-5fe45b5e4e14.transponder_data_colab.flight_transponder_msgs", "fields": 22}

Table ready: qwiklabs-gcp-01-5fe45b5e4e14.transponder_data_colab.flight_transponder_msgs

### Subscribe to the Pub/Sub feed

In [7]:
pipeline.ensure_subscription()
print(f"Subscribed: {CFG.subscription_path}")
print(f"   -> topic: {CFG.topic_path}")

2026-06-02 19:51:10,759 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "subscription_created", "status": "ok", "sub": "projects/qwiklabs-gcp-01-5fe45b5e4e14/subscriptions/flight-transponder-sub-e64e3ef0"}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "subscription_created", "status": "ok", "sub": "projects/qwiklabs-gcp-01-5fe45b5e4e14/subscriptions/flight-transponder-sub-e64e3ef0"}

Subscribed: projects/qwiklabs-gcp-01-5fe45b5e4e14/subscriptions/flight-transponder-sub-e64e3ef0
   -> topic: projects/paul-leroy/topics/flight-transponder

### Collect streaming data — run a few minutes, then stop

This pulls messages, parses each CSV line into the 22-field schema, and stream-inserts
batches into BigQuery. Adjust `run_seconds` as needed (default 3 minutes).

In [8]:
pipeline.collect(run_seconds=180)
print(f"Messages seen : {pipeline.messages_seen:,}")
print(f"Rows inserted : {pipeline.rows_inserted:,}")
print(f"Parse errors  : {pipeline.parse_errors:,}")

2026-06-02 19:51:38,428 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "collect_start", "status": "ok", "run_seconds": 180}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "collect_start", "status": "ok", "run_seconds": 180}

2026-06-02 19:51:43,165 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 200}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 200}

2026-06-02 19:51:45,504 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 400}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 400}

2026-06-02 19:51:52,287 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 282, "total": 682}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 282, "total": 682}

2026-06-02 19:51:54,617 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 882}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 882}

2026-06-02 19:51:58,791 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 288, "total": 1170}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 288, "total": 1170}

2026-06-02 19:52:00,810 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1370}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1370}

2026-06-02 19:52:04,737 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1570}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1570}

2026-06-02 19:52:06,993 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1770}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1770}

2026-06-02 19:52:08,152 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1970}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 1970}

2026-06-02 19:52:12,844 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 207, "total": 2177}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 207, "total": 2177}

2026-06-02 19:52:14,870 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2377}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2377}

2026-06-02 19:52:17,149 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2577}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2577}

2026-06-02 19:52:20,158 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2777}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2777}

2026-06-02 19:52:21,406 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2977}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 2977}

2026-06-02 19:52:23,698 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3177}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3177}

2026-06-02 19:52:27,905 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3377}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3377}

2026-06-02 19:52:29,149 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3577}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3577}

2026-06-02 19:52:31,382 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3777}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3777}

2026-06-02 19:52:33,235 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3977}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 3977}

2026-06-02 19:52:38,335 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 235, "total": 4212}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 235, "total": 4212}

2026-06-02 19:52:40,262 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 4412}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 4412}

2026-06-02 19:52:41,303 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 4612}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 4612}

2026-06-02 19:52:43,816 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 270, "total": 4882}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 270, "total": 4882}

2026-06-02 19:52:45,063 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5082}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5082}

2026-06-02 19:52:45,809 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5282}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5282}

2026-06-02 19:52:47,090 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5482}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5482}

2026-06-02 19:52:48,355 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5682}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5682}

2026-06-02 19:52:48,548 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5882}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 5882}

2026-06-02 19:52:48,740 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6082}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6082}

2026-06-02 19:52:53,397 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 269, "total": 6351}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 269, "total": 6351}

2026-06-02 19:52:54,600 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6551}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6551}

2026-06-02 19:52:55,383 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6751}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6751}

2026-06-02 19:52:56,668 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6951}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 6951}

2026-06-02 19:53:00,296 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 236, "total": 7187}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 236, "total": 7187}

2026-06-02 19:53:01,117 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7387}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7387}

2026-06-02 19:53:02,171 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7587}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7587}

2026-06-02 19:53:03,009 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7787}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7787}

2026-06-02 19:53:03,258 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7987}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 7987}

2026-06-02 19:53:05,623 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8187}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8187}

2026-06-02 19:53:06,879 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8387}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8387}

2026-06-02 19:53:08,038 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8587}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8587}

2026-06-02 19:53:09,139 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8787}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 8787}

2026-06-02 19:53:12,528 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 209, "total": 8996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 209, "total": 8996}

2026-06-02 19:53:14,240 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9196}

2026-06-02 19:53:15,259 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9396}

2026-06-02 19:53:17,305 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9596}

2026-06-02 19:53:19,474 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9796}

2026-06-02 19:53:19,665 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 9996}

2026-06-02 19:53:19,911 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10196}

2026-06-02 19:53:20,639 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10396}

2026-06-02 19:53:20,877 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10596}

2026-06-02 19:53:21,120 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10796}

2026-06-02 19:53:22,309 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 10996}

2026-06-02 19:53:22,555 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11196}

2026-06-02 19:53:24,235 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11396}

2026-06-02 19:53:24,417 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11596}

2026-06-02 19:53:24,550 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11796}

2026-06-02 19:53:26,524 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 11996}

2026-06-02 19:53:26,680 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12196}

2026-06-02 19:53:26,843 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12396}

2026-06-02 19:53:27,574 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12596}

2026-06-02 19:53:27,750 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12796}

2026-06-02 19:53:27,977 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 12996}

2026-06-02 19:53:28,166 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13196}

2026-06-02 19:53:29,323 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13396}

2026-06-02 19:53:30,834 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13596}

2026-06-02 19:53:31,906 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13796}

2026-06-02 19:53:33,871 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 13996}

2026-06-02 19:53:35,061 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14196}

2026-06-02 19:53:35,229 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14396}

2026-06-02 19:53:35,414 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14596}

2026-06-02 19:53:35,608 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14796}

2026-06-02 19:53:35,785 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 14996}

2026-06-02 19:53:35,955 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15196}

2026-06-02 19:53:36,134 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15396}

2026-06-02 19:53:36,404 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15596}

2026-06-02 19:53:36,591 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15796}

2026-06-02 19:53:37,257 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 15996}

2026-06-02 19:53:37,430 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16196}

2026-06-02 19:53:38,385 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16396}

2026-06-02 19:53:38,602 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16596}

2026-06-02 19:53:38,794 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16796}

2026-06-02 19:53:38,983 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 16996}

2026-06-02 19:53:39,157 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17196}

2026-06-02 19:53:40,886 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17396}

2026-06-02 19:53:42,052 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17596}

2026-06-02 19:53:42,223 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17796}

2026-06-02 19:53:42,428 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 17996}

2026-06-02 19:53:42,631 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18196}

2026-06-02 19:53:43,376 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18396}

2026-06-02 19:53:44,446 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18596}

2026-06-02 19:53:44,613 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18796}

2026-06-02 19:53:44,745 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 18996}

2026-06-02 19:53:44,923 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19196}

2026-06-02 19:53:45,112 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19396}

2026-06-02 19:53:45,276 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19596}

2026-06-02 19:53:45,431 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19796}

2026-06-02 19:53:45,581 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 19996}

2026-06-02 19:53:45,771 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20196}

2026-06-02 19:53:45,933 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20396}

2026-06-02 19:53:46,082 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20596}

2026-06-02 19:53:46,243 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20796}

2026-06-02 19:53:46,464 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 20996}

2026-06-02 19:53:47,921 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21196}

2026-06-02 19:53:48,093 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21396}

2026-06-02 19:53:48,305 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21596}

2026-06-02 19:53:48,494 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21796}

2026-06-02 19:53:49,766 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 21996}

2026-06-02 19:53:49,951 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22196}

2026-06-02 19:53:50,117 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22396}

2026-06-02 19:53:50,305 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22596}

2026-06-02 19:53:50,474 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22796}

2026-06-02 19:53:50,667 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 22996}

2026-06-02 19:53:50,796 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23196}

2026-06-02 19:53:50,991 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23396}

2026-06-02 19:53:51,173 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23596}

2026-06-02 19:53:51,324 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23796}

2026-06-02 19:53:51,497 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 23996}

2026-06-02 19:53:51,683 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24196}

2026-06-02 19:53:52,498 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24396}

2026-06-02 19:53:52,641 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24596}

2026-06-02 19:53:52,810 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24796}

2026-06-02 19:53:54,155 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 24996}

2026-06-02 19:53:54,822 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25196}

2026-06-02 19:53:55,007 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25396}

2026-06-02 19:53:56,112 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25596}

2026-06-02 19:53:56,937 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25796}

2026-06-02 19:53:57,129 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 25996}

2026-06-02 19:53:57,293 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26196}

2026-06-02 19:53:57,483 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26396}

2026-06-02 19:53:57,671 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26596}

2026-06-02 19:53:57,842 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26796}

2026-06-02 19:53:57,996 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26996}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 26996}

2026-06-02 19:53:58,154 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27196}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27196}

2026-06-02 19:53:58,296 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27396}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27396}

2026-06-02 19:53:58,457 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27596}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27596}

2026-06-02 19:53:58,594 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27796}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 27796}

2026-06-02 19:54:00,374 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 269, "total": 28065}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 269, "total": 28065}

2026-06-02 19:54:00,563 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28265}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28265}

2026-06-02 19:54:01,435 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28465}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28465}

2026-06-02 19:54:01,680 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28665}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28665}

2026-06-02 19:54:01,880 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28865}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 28865}

2026-06-02 19:54:02,059 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29065}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29065}

2026-06-02 19:54:02,225 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29265}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29265}

2026-06-02 19:54:02,433 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29465}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29465}

2026-06-02 19:54:03,152 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29665}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29665}

2026-06-02 19:54:03,333 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29865}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 29865}

2026-06-02 19:54:03,552 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30065}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30065}

2026-06-02 19:54:03,747 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30265}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30265}

2026-06-02 19:54:03,955 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30465}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30465}

2026-06-02 19:54:04,151 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30665}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30665}

2026-06-02 19:54:04,382 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30865}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 30865}

2026-06-02 19:54:04,553 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31065}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31065}

2026-06-02 19:54:05,484 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31265}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31265}

2026-06-02 19:54:06,760 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31465}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31465}

2026-06-02 19:54:07,081 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31665}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31665}

2026-06-02 19:54:07,255 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31865}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 31865}

2026-06-02 19:54:07,446 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32065}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32065}

2026-06-02 19:54:09,020 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 208, "total": 32273}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 208, "total": 32273}

2026-06-02 19:54:09,776 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32473}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32473}

2026-06-02 19:54:09,889 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32673}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32673}

2026-06-02 19:54:10,047 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32873}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 32873}

2026-06-02 19:54:10,218 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33073}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33073}

2026-06-02 19:54:10,399 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33273}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33273}

2026-06-02 19:54:10,511 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33473}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33473}

2026-06-02 19:54:11,556 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33673}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33673}

2026-06-02 19:54:11,709 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33873}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 33873}

2026-06-02 19:54:11,817 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34073}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34073}

2026-06-02 19:54:11,972 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34273}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34273}

2026-06-02 19:54:12,140 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34473}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34473}

2026-06-02 19:54:12,324 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34673}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34673}

2026-06-02 19:54:12,482 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34873}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 34873}

2026-06-02 19:54:12,631 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35073}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35073}

2026-06-02 19:54:12,790 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35273}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35273}

2026-06-02 19:54:12,928 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35473}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35473}

2026-06-02 19:54:13,103 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35673}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35673}

2026-06-02 19:54:13,299 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35873}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 35873}

2026-06-02 19:54:13,465 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 36073}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 36073}

2026-06-02 19:54:13,666 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 36273}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 36273}

2026-06-02 19:54:15,402 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 208, "total": 36481}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 208, "total": 36481}

2026-06-02 19:54:15,573 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 36681}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 36681}

2026-06-02 19:54:17,419 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 230, "total": 36911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 230, "total": 36911}

2026-06-02 19:54:17,577 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37111}

2026-06-02 19:54:17,774 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37311}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37311}

2026-06-02 19:54:17,934 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37511}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37511}

2026-06-02 19:54:18,143 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37711}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37711}

2026-06-02 19:54:18,358 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 37911}

2026-06-02 19:54:18,532 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38111}

2026-06-02 19:54:19,598 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38311}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38311}

2026-06-02 19:54:19,757 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38511}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38511}

2026-06-02 19:54:19,903 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38711}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38711}

2026-06-02 19:54:20,067 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 38911}

2026-06-02 19:54:20,260 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39111}

2026-06-02 19:54:20,430 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39311}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39311}

2026-06-02 19:54:20,646 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39511}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39511}

2026-06-02 19:54:20,841 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39711}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39711}

2026-06-02 19:54:21,022 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 39911}

2026-06-02 19:54:21,204 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40111}

2026-06-02 19:54:21,333 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40311}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40311}

2026-06-02 19:54:21,482 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40511}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40511}

2026-06-02 19:54:21,656 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40711}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40711}

2026-06-02 19:54:21,831 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 40911}

2026-06-02 19:54:22,005 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41111}

2026-06-02 19:54:22,246 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41311}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41311}

2026-06-02 19:54:22,394 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41511}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41511}

2026-06-02 19:54:22,505 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41711}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41711}

2026-06-02 19:54:22,655 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 41911}

2026-06-02 19:54:22,819 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42111}

2026-06-02 19:54:22,991 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42311}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42311}

2026-06-02 19:54:23,198 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42511}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42511}

2026-06-02 19:54:23,323 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42711}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42711}

2026-06-02 19:54:23,475 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42911}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 42911}

2026-06-02 19:54:23,627 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 43111}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 43111}

2026-06-02 19:54:25,329 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 261, "total": 43372}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 261, "total": 43372}

2026-06-02 19:54:25,501 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 43572}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 43572}

2026-06-02 19:54:27,112 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 230, "total": 43802}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 230, "total": 43802}

2026-06-02 19:54:27,300 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44002}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44002}

2026-06-02 19:54:27,465 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44202}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44202}

2026-06-02 19:54:27,620 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44402}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44402}

2026-06-02 19:54:27,780 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44602}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44602}

2026-06-02 19:54:27,955 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44802}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 44802}

2026-06-02 19:54:28,111 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45002}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45002}

2026-06-02 19:54:28,281 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45202}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45202}

2026-06-02 19:54:28,452 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45402}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45402}

2026-06-02 19:54:28,628 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45602}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45602}

2026-06-02 19:54:28,790 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45802}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 45802}

2026-06-02 19:54:28,979 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46002}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46002}

2026-06-02 19:54:29,152 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46202}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46202}

2026-06-02 19:54:29,350 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46402}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46402}

2026-06-02 19:54:29,500 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46602}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46602}

2026-06-02 19:54:29,664 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46802}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 46802}

2026-06-02 19:54:29,866 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47002}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47002}

2026-06-02 19:54:30,063 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47202}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47202}

2026-06-02 19:54:30,178 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47402}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47402}

2026-06-02 19:54:30,371 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47602}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47602}

2026-06-02 19:54:30,539 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47802}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 47802}

2026-06-02 19:54:30,713 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48002}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48002}

2026-06-02 19:54:30,886 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48202}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48202}

2026-06-02 19:54:31,197 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48402}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48402}

2026-06-02 19:54:31,340 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48602}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 48602}

2026-06-02 19:54:31,778 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 216, "total": 48818}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 216, "total": 48818}

2026-06-02 19:54:32,914 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 207, "total": 49025}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 207, "total": 49025}

2026-06-02 19:54:34,116 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 250, "total": 49275}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 250, "total": 49275}

2026-06-02 19:54:34,956 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 49475}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 200, "total": 49475}

2026-06-02 19:54:36,031 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 251, "total": 49726}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 251, "total": 49726}

2026-06-02 19:54:37,411 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 221, "total": 49947}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 221, "total": 49947}

2026-06-02 19:54:38,386 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 223, "total": 50170}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 223, "total": 50170}

2026-06-02 19:54:38,539 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 15, "total": 50185}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "flush", "status": "ok", "inserted": 15, "total": 50185}

2026-06-02 19:54:38,541 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "collect_done", "status": "ok", "messages_seen": 50185, "rows_inserted": 50185, "parse_errors": 0}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "collect_done", "status": "ok", "messages_seen": 50185, "rows_inserted": 50185, "parse_errors": 0}

Messages seen : 50,185
Rows inserted : 50,185
Parse errors  : 0

### Preview the accumulated data

In [9]:
pipeline.preview()

2026-06-02 19:58:15,219 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "preview", "status": "ok", "rows": 10}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "preview", "status": "ok", "rows": 10}

,MT,TT,SID,AID,Hex,FID,DMG,TMG,DML,TML,...,GS,Trk,Lat,Lng,VR,Sq,Alrt,Emer,SPI,Gnd
0,MSG,7,1,1,400846,1,2026-06-02,19:51:10.439000,2026-06-02,19:51:10.487000,...,<NA>,<NA>,NaN,NaN,<NA>,None,<NA>,<NA>,<NA>,<NA>
1,MSG,7,1,1,010207,1,2026-06-02,19:51:10.445000,2026-06-02,19:51:10.487000,...,<NA>,<NA>,NaN,NaN,<NA>,None,<NA>,<NA>,<NA>,<NA>
2,MSG,4,1,1,4CAD7A,1,2026-06-02,19:51:10.450000,2026-06-02,19:51:10.487000,...,330,294,NaN,NaN,3200,None,<NA>,<NA>,<NA>,<NA>
3,MSG,3,1,1,3C5428,1,2026-06-02,19:51:10.451000,2026-06-02,19:51:10.488000,...,<NA>,<NA>,50.89468,0.71777,<NA>,None,0,<NA>,0,0
4,MSG,5,1,1,39E698,1,2026-06-02,19:51:10.451000,2026-06-02,19:51:10.488000,...,<NA>,<NA>,NaN,NaN,<NA>,None,0,<NA>,0,<NA>
5,MSG,7,1,1,4077E0,1,2026-06-02,19:51:10.452000,2026-06-02,19:51:10.488000,...,<NA>,<NA>,NaN,NaN,<NA>,None,<NA>,<NA>,<NA>,<NA>
6,MSG,5,1,1,40631B,1,2026-06-02,19:51:10.461000,2026-06-02,19:51:10.488000,...,<NA>,<NA>,NaN,NaN,<NA>,None,0,<NA>,0,<NA>
7,MSG,5,1,1,406CD2,1,2026-06-02,19:51:10.462000,2026-06-02,19:51:10.488000,...,<NA>,<NA>,NaN,NaN,<NA>,None,0,<NA>,0,<NA>
8,MSG,8,1,1,405B66,1,2026-06-02,19:51:10.470000,2026-06-02,19:51:10.488000,...,<NA>,<NA>,NaN,NaN,<NA>,None,<NA>,<NA>,<NA>,<NA>
9,MSG,7,1,1,406CD2,1,2026-06-02,19:51:10.476000,2026-06-02,19:51:10.489000,...,<NA>,<NA>,NaN,NaN,<NA>,None,<NA>,<NA>,<NA>,<NA>

### Step 5 — Count the records

In [10]:
pipeline.count_records()

2026-06-02 19:58:36,913 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "count_records", "status": "ok", "count": 50185}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "count_records", "status": "ok", "count": 50185}

   record_count
0         50185

### Step 6 — Locations query for Geo Viz

In [11]:
locations_sql = f"""
SELECT
  ST_GEOGPOINT(Lng, Lat) AS Location
FROM `{CFG.table}`
WHERE Lat IS NOT NULL
  AND Lng IS NOT NULL
"""
print(locations_sql)

# Also pull the points into a dataframe so we can confirm they look right.
pipeline.locations().head()

SELECT
  ST_GEOGPOINT(Lng, Lat) AS Location
FROM `qwiklabs-gcp-01-5fe45b5e4e14.transponder_data_colab.flight_transponder_msgs`
WHERE Lat IS NOT NULL
  AND Lng IS NOT NULL

2026-06-02 19:59:05,266 | INFO | {"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "locations", "status": "ok", "points": 2924}

INFO:flight_transponder_stream:{"run_id": "043eeb1b-473c-4ca9-afa5-c1a1c36c796f", "step": "locations", "status": "ok", "points": 2924}

                   Location
0   POINT(0.71777 50.89468)
1   POINT(-0.3042 51.78621)
2   POINT(0.23087 51.64431)
3  POINT(-1.33573 51.50281)
4  POINT(-0.16068 51.28539)